version: '3'
services:
  db:
    image: postgres:latest
    container_name: Database
    environment:
      POSTGRES_DB: ControleAcesso
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
    ports:
      - "5432:5432"

  app:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: ControleAcesso
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      DATABASE: Host=db;Database=ControleAcesso;Username=your_database_user;Password=senha
      SECRET: thisisasecrettojwt
